/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BadgeBaseProps } from "./components/badge/badge.types";
import { BrandProps } from "./components/brand/brand.types";
import { ButtonIconProps, ButtonProps } from "./components/button/button.types";
import { DatePickerMode, DateRange, DateSelectedEventDetail, MonthYear } from "./components/date-picker/date-picker.types";
import { FieldNumberVariant } from "./components/field-number/field-number.types";
import { SizeVariants } from "./shared/theme/theme.types";
import { FieldTextProps } from "./components/field-text/field-text.types";
import { IconLargeProps, IconProps } from "./components/icon/icon.types";
import { IllustrationProps } from "./components/illustration/illustration.types";
import { StepItem, StepsProps, StepStatus } from "./components/steps/steps.types";
import { SwitchBaseProps, SwitchChangeEventDetail, SwitchType } from "./components/switch/switch.types";
import { TabItemProps } from "./components/tab-item/tab-item.types";
import { TabItem, TabItemGroupProps } from "./components/tab-item-group/tab-item-group.types";
import { TooltipProps } from "./components/tooltip/tooltip.types";
export { BadgeBaseProps } from "./components/badge/badge.types";
export { BrandProps } from "./components/brand/brand.types";
export { ButtonIconProps, ButtonProps } from "./components/button/button.types";
export { DatePickerMode, DateRange, DateSelectedEventDetail, MonthYear } from "./components/date-picker/date-picker.types";
export { FieldNumberVariant } from "./components/field-number/field-number.types";
export { SizeVariants } from "./shared/theme/theme.types";
export { FieldTextProps } from "./components/field-text/field-text.types";
export { IconLargeProps, IconProps } from "./components/icon/icon.types";
export { IllustrationProps } from "./components/illustration/illustration.types";
export { StepItem, StepsProps, StepStatus } from "./components/steps/steps.types";
export { SwitchBaseProps, SwitchChangeEventDetail, SwitchType } from "./components/switch/switch.types";
export { TabItemProps } from "./components/tab-item/tab-item.types";
export { TabItem, TabItemGroupProps } from "./components/tab-item-group/tab-item-group.types";
export { TooltipProps } from "./components/tooltip/tooltip.types";
export namespace Components {
    interface MntBadge {
        "color"?: BadgeBaseProps['color'];
        "icon"?: BadgeBaseProps['icon'];
        "label": BadgeBaseProps['label'];
        "size"?: BadgeBaseProps['size'];
        "tone"?: BadgeBaseProps['tone'];
    }
    interface MntBrand {
        "color": BrandProps['color'];
        "height": BrandProps['height'];
        "name": BrandProps['name'];
    }
    interface MntButton {
        "color": ButtonProps['color'];
        "disabled": ButtonProps['disabled'];
        "fullWidth": ButtonProps['fullWidth'];
        "iconAnimation"?: ButtonProps['iconAnimation'];
        "iconLeft"?: ButtonProps['iconLeft'];
        "iconRight"?: ButtonProps['iconRight'];
        "label"?: ButtonProps['label'];
        "size": ButtonProps['size'];
        "variant": ButtonProps['variant'];
    }
    interface MntButtonIcon {
        "color": ButtonIconProps['color'];
        "disabled": ButtonIconProps['disabled'];
        "icon"?: ButtonIconProps['icon'];
        "size": ButtonIconProps['size'];
        "variant": ButtonIconProps['variant'];
    }
    interface MntDatePicker {
        "disablePastDates"?: boolean;
        "disabled"?: boolean;
        "firstDayOfWeek"?: number;
        "initialMonth"?: Date | string | null;
        "locale"?: string;
        "maxDate"?: Date | string | null;
        "minDate"?: Date | string | null;
        "mode"?: DatePickerMode;
        "placeholder"?: string;
        "required"?: boolean;
        "selectedDate"?: Date | string | null;
        "selectedRange"?: DateRange | null;
    }
    interface MntFieldNumber {
        "disabled"?: boolean;
        "inputName": string;
        "label"?: string;
        "max"?: number;
        "min"?: number;
        "required"?: boolean;
        "size"?: Exclude<SizeVariants, 'tiny'>;
        "step"?: number;
        "value": string;
        "variant"?: FieldNumberVariant;
    }
    interface MntFieldText {
        "disabled"?: FieldTextProps['disabled'];
        "hasActionButton"?: FieldTextProps['hasActionButton'];
        "hasInfoButton"?: FieldTextProps['hasInfoButton'];
        "iconLeft"?: FieldTextProps['iconLeft'];
        "iconRight"?: FieldTextProps['iconRight'];
        "inlineMessage"?: FieldTextProps['inlineMessage'];
        "inputName": string;
        "labelText"?: FieldTextProps['labelText'];
        "mask"?: 'currency' | 'custom';
        "max"?: number;
        "maxLength"?: number;
        "min"?: number;
        "minLength"?: number;
        "placeholder"?: FieldTextProps['placeholder'];
        "required"?: FieldTextProps['required'];
        "size"?: FieldTextProps['size'];
        "state"?: FieldTextProps['state'];
        "value"?: string;
    }
    interface MntIcon {
        "animation"?: IconProps['animation'];
        "background"?: IconProps['background'];
        "bgShape"?: IconProps['bgShape'];
        "color": IconProps['color'];
        "icon": IconProps['icon'];
        "size": IconProps['size'];
    }
    interface MntIconLarge {
        "color": IconLargeProps['color'];
        "icon": string;
        "size": IconLargeProps['size'];
    }
    interface MntIllustration {
        "height": IllustrationProps['height'];
        "name": IllustrationProps['name'];
        "width": IllustrationProps['width'];
    }
    interface MntSteps {
        "activeStepId"?: StepsProps['activeStepId'];
        "orientation": StepsProps['orientation'];
        "steps": StepsProps['steps'];
    }
    interface MntSwitch {
        "checked"?: SwitchBaseProps['checked'];
        "description"?: SwitchBaseProps['description'];
        "disabled"?: SwitchBaseProps['disabled'];
        "inputId"?: SwitchBaseProps['inputId'];
        "label"?: SwitchBaseProps['label'];
        "name"?: SwitchBaseProps['name'];
        "required"?: SwitchBaseProps['required'];
        "type"?: SwitchType;
        "value"?: SwitchBaseProps['value'];
    }
    interface MntTabItem {
        "disabled": boolean;
        "icon"?: TabItemProps['icon'];
        "label": string;
        "orientation": TabItemProps['orientation'];
        "selected": boolean;
        "tabId": string;
    }
    interface MntTabItemGroup {
        "orientation": TabItemGroupProps['orientation'];
        "selectedId"?: string;
        "tabs": TabItem[] | string;
    }
    interface MntTooltip {
        "position": TooltipProps['position'];
        "text": TooltipProps['text'];
    }
}
export interface MntButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntButtonElement;
}
export interface MntButtonIconCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntButtonIconElement;
}
export interface MntDatePickerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntDatePickerElement;
}
export interface MntFieldTextCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntFieldTextElement;
}
export interface MntStepsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntStepsElement;
}
export interface MntSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntSwitchElement;
}
export interface MntTabItemCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntTabItemElement;
}
export interface MntTabItemGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMntTabItemGroupElement;
}
declare global {
    interface HTMLMntBadgeElement extends Components.MntBadge, HTMLStencilElement {
    }
    var HTMLMntBadgeElement: {
        prototype: HTMLMntBadgeElement;
        new (): HTMLMntBadgeElement;
    };
    interface HTMLMntBrandElement extends Components.MntBrand, HTMLStencilElement {
    }
    var HTMLMntBrandElement: {
        prototype: HTMLMntBrandElement;
        new (): HTMLMntBrandElement;
    };
    interface HTMLMntButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLMntButtonElement extends Components.MntButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntButtonElementEventMap>(type: K, listener: (this: HTMLMntButtonElement, ev: MntButtonCustomEvent<HTMLMntButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntButtonElementEventMap>(type: K, listener: (this: HTMLMntButtonElement, ev: MntButtonCustomEvent<HTMLMntButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntButtonElement: {
        prototype: HTMLMntButtonElement;
        new (): HTMLMntButtonElement;
    };
    interface HTMLMntButtonIconElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLMntButtonIconElement extends Components.MntButtonIcon, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntButtonIconElementEventMap>(type: K, listener: (this: HTMLMntButtonIconElement, ev: MntButtonIconCustomEvent<HTMLMntButtonIconElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntButtonIconElementEventMap>(type: K, listener: (this: HTMLMntButtonIconElement, ev: MntButtonIconCustomEvent<HTMLMntButtonIconElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntButtonIconElement: {
        prototype: HTMLMntButtonIconElement;
        new (): HTMLMntButtonIconElement;
    };
    interface HTMLMntDatePickerElementEventMap {
        "datePickerSelected": DateSelectedEventDetail;
        "datePickerCancel": void;
        "datePickerMonthChange": MonthYear;
    }
    interface HTMLMntDatePickerElement extends Components.MntDatePicker, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntDatePickerElementEventMap>(type: K, listener: (this: HTMLMntDatePickerElement, ev: MntDatePickerCustomEvent<HTMLMntDatePickerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntDatePickerElementEventMap>(type: K, listener: (this: HTMLMntDatePickerElement, ev: MntDatePickerCustomEvent<HTMLMntDatePickerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntDatePickerElement: {
        prototype: HTMLMntDatePickerElement;
        new (): HTMLMntDatePickerElement;
    };
    interface HTMLMntFieldNumberElement extends Components.MntFieldNumber, HTMLStencilElement {
    }
    var HTMLMntFieldNumberElement: {
        prototype: HTMLMntFieldNumberElement;
        new (): HTMLMntFieldNumberElement;
    };
    interface HTMLMntFieldTextElementEventMap {
        "valueChange": string;
        "rawValueChange": string;
    }
    interface HTMLMntFieldTextElement extends Components.MntFieldText, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntFieldTextElementEventMap>(type: K, listener: (this: HTMLMntFieldTextElement, ev: MntFieldTextCustomEvent<HTMLMntFieldTextElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntFieldTextElementEventMap>(type: K, listener: (this: HTMLMntFieldTextElement, ev: MntFieldTextCustomEvent<HTMLMntFieldTextElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntFieldTextElement: {
        prototype: HTMLMntFieldTextElement;
        new (): HTMLMntFieldTextElement;
    };
    interface HTMLMntIconElement extends Components.MntIcon, HTMLStencilElement {
    }
    var HTMLMntIconElement: {
        prototype: HTMLMntIconElement;
        new (): HTMLMntIconElement;
    };
    interface HTMLMntIconLargeElement extends Components.MntIconLarge, HTMLStencilElement {
    }
    var HTMLMntIconLargeElement: {
        prototype: HTMLMntIconLargeElement;
        new (): HTMLMntIconLargeElement;
    };
    interface HTMLMntIllustrationElement extends Components.MntIllustration, HTMLStencilElement {
    }
    var HTMLMntIllustrationElement: {
        prototype: HTMLMntIllustrationElement;
        new (): HTMLMntIllustrationElement;
    };
    interface HTMLMntStepsElementEventMap {
        "stepClick": { stepId: string; stepIndex: number; status: StepStatus; step: StepItem };
    }
    interface HTMLMntStepsElement extends Components.MntSteps, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntStepsElementEventMap>(type: K, listener: (this: HTMLMntStepsElement, ev: MntStepsCustomEvent<HTMLMntStepsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntStepsElementEventMap>(type: K, listener: (this: HTMLMntStepsElement, ev: MntStepsCustomEvent<HTMLMntStepsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntStepsElement: {
        prototype: HTMLMntStepsElement;
        new (): HTMLMntStepsElement;
    };
    interface HTMLMntSwitchElementEventMap {
        "onChange": SwitchChangeEventDetail;
        "onBlur": FocusEvent;
        "onFocus": FocusEvent;
    }
    interface HTMLMntSwitchElement extends Components.MntSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntSwitchElementEventMap>(type: K, listener: (this: HTMLMntSwitchElement, ev: MntSwitchCustomEvent<HTMLMntSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntSwitchElementEventMap>(type: K, listener: (this: HTMLMntSwitchElement, ev: MntSwitchCustomEvent<HTMLMntSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntSwitchElement: {
        prototype: HTMLMntSwitchElement;
        new (): HTMLMntSwitchElement;
    };
    interface HTMLMntTabItemElementEventMap {
        "tabItemClick": string;
    }
    interface HTMLMntTabItemElement extends Components.MntTabItem, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntTabItemElementEventMap>(type: K, listener: (this: HTMLMntTabItemElement, ev: MntTabItemCustomEvent<HTMLMntTabItemElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntTabItemElementEventMap>(type: K, listener: (this: HTMLMntTabItemElement, ev: MntTabItemCustomEvent<HTMLMntTabItemElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntTabItemElement: {
        prototype: HTMLMntTabItemElement;
        new (): HTMLMntTabItemElement;
    };
    interface HTMLMntTabItemGroupElementEventMap {
        "tabChange": string;
    }
    interface HTMLMntTabItemGroupElement extends Components.MntTabItemGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMntTabItemGroupElementEventMap>(type: K, listener: (this: HTMLMntTabItemGroupElement, ev: MntTabItemGroupCustomEvent<HTMLMntTabItemGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMntTabItemGroupElementEventMap>(type: K, listener: (this: HTMLMntTabItemGroupElement, ev: MntTabItemGroupCustomEvent<HTMLMntTabItemGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMntTabItemGroupElement: {
        prototype: HTMLMntTabItemGroupElement;
        new (): HTMLMntTabItemGroupElement;
    };
    interface HTMLMntTooltipElement extends Components.MntTooltip, HTMLStencilElement {
    }
    var HTMLMntTooltipElement: {
        prototype: HTMLMntTooltipElement;
        new (): HTMLMntTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "mnt-badge": HTMLMntBadgeElement;
        "mnt-brand": HTMLMntBrandElement;
        "mnt-button": HTMLMntButtonElement;
        "mnt-button-icon": HTMLMntButtonIconElement;
        "mnt-date-picker": HTMLMntDatePickerElement;
        "mnt-field-number": HTMLMntFieldNumberElement;
        "mnt-field-text": HTMLMntFieldTextElement;
        "mnt-icon": HTMLMntIconElement;
        "mnt-icon-large": HTMLMntIconLargeElement;
        "mnt-illustration": HTMLMntIllustrationElement;
        "mnt-steps": HTMLMntStepsElement;
        "mnt-switch": HTMLMntSwitchElement;
        "mnt-tab-item": HTMLMntTabItemElement;
        "mnt-tab-item-group": HTMLMntTabItemGroupElement;
        "mnt-tooltip": HTMLMntTooltipElement;
    }
}
declare namespace LocalJSX {
    interface MntBadge {
        "color"?: BadgeBaseProps['color'];
        "icon"?: BadgeBaseProps['icon'];
        "label"?: BadgeBaseProps['label'];
        "size"?: BadgeBaseProps['size'];
        "tone"?: BadgeBaseProps['tone'];
    }
    interface MntBrand {
        "color"?: BrandProps['color'];
        "height"?: BrandProps['height'];
        "name": BrandProps['name'];
    }
    interface MntButton {
        "color"?: ButtonProps['color'];
        "disabled"?: ButtonProps['disabled'];
        "fullWidth"?: ButtonProps['fullWidth'];
        "iconAnimation"?: ButtonProps['iconAnimation'];
        "iconLeft"?: ButtonProps['iconLeft'];
        "iconRight"?: ButtonProps['iconRight'];
        "label"?: ButtonProps['label'];
        "onButtonClick"?: (event: MntButtonCustomEvent<MouseEvent>) => void;
        "size"?: ButtonProps['size'];
        "variant"?: ButtonProps['variant'];
    }
    interface MntButtonIcon {
        "color"?: ButtonIconProps['color'];
        "disabled"?: ButtonIconProps['disabled'];
        "icon"?: ButtonIconProps['icon'];
        "onButtonClick"?: (event: MntButtonIconCustomEvent<MouseEvent>) => void;
        "size"?: ButtonIconProps['size'];
        "variant"?: ButtonIconProps['variant'];
    }
    interface MntDatePicker {
        "disablePastDates"?: boolean;
        "disabled"?: boolean;
        "firstDayOfWeek"?: number;
        "initialMonth"?: Date | string | null;
        "locale"?: string;
        "maxDate"?: Date | string | null;
        "minDate"?: Date | string | null;
        "mode"?: DatePickerMode;
        "onDatePickerCancel"?: (event: MntDatePickerCustomEvent<void>) => void;
        "onDatePickerMonthChange"?: (event: MntDatePickerCustomEvent<MonthYear>) => void;
        "onDatePickerSelected"?: (event: MntDatePickerCustomEvent<DateSelectedEventDetail>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "selectedDate"?: Date | string | null;
        "selectedRange"?: DateRange | null;
    }
    interface MntFieldNumber {
        "disabled"?: boolean;
        "inputName": string;
        "label"?: string;
        "max"?: number;
        "min"?: number;
        "required"?: boolean;
        "size"?: Exclude<SizeVariants, 'tiny'>;
        "step"?: number;
        "value"?: string;
        "variant"?: FieldNumberVariant;
    }
    interface MntFieldText {
        "disabled"?: FieldTextProps['disabled'];
        "hasActionButton"?: FieldTextProps['hasActionButton'];
        "hasInfoButton"?: FieldTextProps['hasInfoButton'];
        "iconLeft"?: FieldTextProps['iconLeft'];
        "iconRight"?: FieldTextProps['iconRight'];
        "inlineMessage"?: FieldTextProps['inlineMessage'];
        "inputName"?: string;
        "labelText"?: FieldTextProps['labelText'];
        "mask"?: 'currency' | 'custom';
        "max"?: number;
        "maxLength"?: number;
        "min"?: number;
        "minLength"?: number;
        /**
          * Evento emitido com o valor numérico (sem formatação) quando o campo é alterado
         */
        "onRawValueChange"?: (event: MntFieldTextCustomEvent<string>) => void;
        "onValueChange"?: (event: MntFieldTextCustomEvent<string>) => void;
        "placeholder"?: FieldTextProps['placeholder'];
        "required"?: FieldTextProps['required'];
        "size"?: FieldTextProps['size'];
        "state"?: FieldTextProps['state'];
        "value"?: string;
    }
    interface MntIcon {
        "animation"?: IconProps['animation'];
        "background"?: IconProps['background'];
        "bgShape"?: IconProps['bgShape'];
        "color"?: IconProps['color'];
        "icon": IconProps['icon'];
        "size"?: IconProps['size'];
    }
    interface MntIconLarge {
        "color"?: IconLargeProps['color'];
        "icon": string;
        "size"?: IconLargeProps['size'];
    }
    interface MntIllustration {
        "height"?: IllustrationProps['height'];
        "name": IllustrationProps['name'];
        "width"?: IllustrationProps['width'];
    }
    interface MntSteps {
        "activeStepId"?: StepsProps['activeStepId'];
        "onStepClick"?: (event: MntStepsCustomEvent<{ stepId: string; stepIndex: number; status: StepStatus; step: StepItem }>) => void;
        "orientation"?: StepsProps['orientation'];
        "steps"?: StepsProps['steps'];
    }
    interface MntSwitch {
        "checked"?: SwitchBaseProps['checked'];
        "description"?: SwitchBaseProps['description'];
        "disabled"?: SwitchBaseProps['disabled'];
        "inputId"?: SwitchBaseProps['inputId'];
        "label"?: SwitchBaseProps['label'];
        "name"?: SwitchBaseProps['name'];
        "onOnBlur"?: (event: MntSwitchCustomEvent<FocusEvent>) => void;
        "onOnChange"?: (event: MntSwitchCustomEvent<SwitchChangeEventDetail>) => void;
        "onOnFocus"?: (event: MntSwitchCustomEvent<FocusEvent>) => void;
        "required"?: SwitchBaseProps['required'];
        "type"?: SwitchType;
        "value"?: SwitchBaseProps['value'];
    }
    interface MntTabItem {
        "disabled"?: boolean;
        "icon"?: TabItemProps['icon'];
        "label": string;
        "onTabItemClick"?: (event: MntTabItemCustomEvent<string>) => void;
        "orientation"?: TabItemProps['orientation'];
        "selected"?: boolean;
        "tabId": string;
    }
    interface MntTabItemGroup {
        "onTabChange"?: (event: MntTabItemGroupCustomEvent<string>) => void;
        "orientation"?: TabItemGroupProps['orientation'];
        "selectedId"?: string;
        "tabs": TabItem[] | string;
    }
    interface MntTooltip {
        "position"?: TooltipProps['position'];
        "text"?: TooltipProps['text'];
    }
    interface IntrinsicElements {
        "mnt-badge": MntBadge;
        "mnt-brand": MntBrand;
        "mnt-button": MntButton;
        "mnt-button-icon": MntButtonIcon;
        "mnt-date-picker": MntDatePicker;
        "mnt-field-number": MntFieldNumber;
        "mnt-field-text": MntFieldText;
        "mnt-icon": MntIcon;
        "mnt-icon-large": MntIconLarge;
        "mnt-illustration": MntIllustration;
        "mnt-steps": MntSteps;
        "mnt-switch": MntSwitch;
        "mnt-tab-item": MntTabItem;
        "mnt-tab-item-group": MntTabItemGroup;
        "mnt-tooltip": MntTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mnt-badge": LocalJSX.MntBadge & JSXBase.HTMLAttributes<HTMLMntBadgeElement>;
            "mnt-brand": LocalJSX.MntBrand & JSXBase.HTMLAttributes<HTMLMntBrandElement>;
            "mnt-button": LocalJSX.MntButton & JSXBase.HTMLAttributes<HTMLMntButtonElement>;
            "mnt-button-icon": LocalJSX.MntButtonIcon & JSXBase.HTMLAttributes<HTMLMntButtonIconElement>;
            "mnt-date-picker": LocalJSX.MntDatePicker & JSXBase.HTMLAttributes<HTMLMntDatePickerElement>;
            "mnt-field-number": LocalJSX.MntFieldNumber & JSXBase.HTMLAttributes<HTMLMntFieldNumberElement>;
            "mnt-field-text": LocalJSX.MntFieldText & JSXBase.HTMLAttributes<HTMLMntFieldTextElement>;
            "mnt-icon": LocalJSX.MntIcon & JSXBase.HTMLAttributes<HTMLMntIconElement>;
            "mnt-icon-large": LocalJSX.MntIconLarge & JSXBase.HTMLAttributes<HTMLMntIconLargeElement>;
            "mnt-illustration": LocalJSX.MntIllustration & JSXBase.HTMLAttributes<HTMLMntIllustrationElement>;
            "mnt-steps": LocalJSX.MntSteps & JSXBase.HTMLAttributes<HTMLMntStepsElement>;
            "mnt-switch": LocalJSX.MntSwitch & JSXBase.HTMLAttributes<HTMLMntSwitchElement>;
            "mnt-tab-item": LocalJSX.MntTabItem & JSXBase.HTMLAttributes<HTMLMntTabItemElement>;
            "mnt-tab-item-group": LocalJSX.MntTabItemGroup & JSXBase.HTMLAttributes<HTMLMntTabItemGroupElement>;
            "mnt-tooltip": LocalJSX.MntTooltip & JSXBase.HTMLAttributes<HTMLMntTooltipElement>;
        }
    }
}
